# Generated by Django 5.1.4 on 2025-01-05 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcart',
            name='thread_discount',
        ),
        migrations.RemoveField(
            model_name='aboutcart',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='aboutcart',
            name='thread_user',
        ),
        migrations.RemoveField(
            model_name='aboutorder',
            name='thread_discount',
        ),
        migrations.RemoveField(
            model_name='aboutorder',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='aboutorder',
            name='thread_status',
        ),
        migrations.RemoveField(
            model_name='aboutorder',
            name='thread_user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
