# Generated by Django 5.1.4 on 2025-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_district_region_address_delete_deliveryprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
