# Generated by Django 5.1.4 on 2025-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutorder',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10, null=True),
        ),
    ]
